package com.gymmanagement.service;

import com.gymmanagement.dao.GymMerchDAO;
import com.gymmanagement.model.GymMerch;
import com.gymmanagement.util.LoggerUtil;

import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Logger;

/**
 * Service class for managing gym merchandise operations.
 * Acts as a facade between the application and the data access layer (DAO).
 * Provides business logic for merchandise management and inventory tracking.
 */
public class GymMerchService {

    private final GymMerchDAO gymMerchDAO;
    private static final Logger LOGGER = LoggerUtil.getLogger();

    /**
     * Default constructor that initializes the GymMerchDAO.
     */
    public GymMerchService() {
        this.gymMerchDAO = new GymMerchDAO();
    }

    /**
     * Constructor that accepts a GymMerchDAO instance (useful for dependency injection and testing).
     * 
     * @param gymMerchDAO the DAO instance for merchandise database operations
     */
    public GymMerchService(GymMerchDAO gymMerchDAO) {
        this.gymMerchDAO = gymMerchDAO;
    }

    /**
     * Adds a new merchandise item to the gym's inventory.
     * Creates a GymMerch object with the provided details and delegates to the DAO.
     * 
     * @param name the name of the merchandise
     * @param type the type/category of merchandise
     * @param price the price of the merchandise
     * @param quantity the initial quantity in stock
     * @return the created GymMerch object with the generated ID, or null if creation fails
     */
    public GymMerch addMerchItem(String name, String type, BigDecimal price, int quantity) {
        // Create a new GymMerch object with provided details (ID starts at 0, will be generated by DB)
        GymMerch merch = new GymMerch(0, name, type, price, quantity);
        // Delegate to DAO to persist the merchandise
        GymMerch created = gymMerchDAO.createMerch(merch);
        // Log the result of the operation
        if (created != null) {
            LOGGER.info("Merch item added: " + name + ", quantity=" + quantity);
        } else {
            LOGGER.warning("Merch item add failed: " + name);
        }
        return created;
    }

    /**
     * Retrieves all merchandise items from the inventory.
     * 
     * @return a list of all GymMerch objects, or empty list if none found
     */
    public List<GymMerch> getAllMerch() {
        return gymMerchDAO.getAllMerch();
    }

    /**
     * Calculates the total monetary value of all merchandise currently in stock.
     * Formula: sum of (price * quantity) for all merchandise items.
     * 
     * @return the total stock value as BigDecimal, or zero if no merchandise or on error
     */
    public BigDecimal getTotalStockValue() {
        return gymMerchDAO.getTotalStockValue();
    }
}
