package com.gymmanagement.service;

import com.gymmanagement.dao.MembershipDAO;
import com.gymmanagement.model.Membership;
import com.gymmanagement.util.LoggerUtil;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Logger;

/**
 * Service class for managing gym membership operations.
 * Acts as a facade between the application and the data access layer (DAO).
 * Provides business logic for membership purchases, tracking, and revenue calculation.
 */
public class MembershipService {

    private final MembershipDAO membershipDAO;
    private static final Logger LOGGER = LoggerUtil.getLogger();

    /**
     * Default constructor that initializes the MembershipDAO.
     */
    public MembershipService() {
        this.membershipDAO = new MembershipDAO();
    }

    /**
     * Constructor that accepts a MembershipDAO instance (useful for dependency injection and testing).
     * 
     * @param membershipDAO the DAO instance for membership database operations
     */
    public MembershipService(MembershipDAO membershipDAO) {
        this.membershipDAO = membershipDAO;
    }

    /**
     * Processes a membership purchase for a member.
     * Calculates start and end dates based on the duration in months.
     * Creates and persists the membership record.
     * 
     * @param memberId the ID of the member purchasing the membership
     * @param type the type of membership (e.g., Monthly, Annual)
     * @param description the description of membership benefits
     * @param cost the cost of the membership
     * @param durationMonths the duration of the membership in months
     * @return the created Membership object with the generated ID, or null if purchase fails
     */
    public Membership purchaseMembership(int memberId,
                                         String type,
                                         String description,
                                         BigDecimal cost,
                                         int durationMonths) {

        // Calculate membership validity period
        LocalDate startDate = LocalDate.now();
        LocalDate endDate = startDate.plusMonths(durationMonths);

        // Create a new Membership object with the calculated dates
        Membership membership = new Membership(
                0,  // ID will be generated by the database
                type,
                description,
                cost,
                memberId,
                startDate,
                endDate
        );

        // Delegate to DAO to persist the membership
        Membership created = membershipDAO.createMembership(membership);
        // Log the result of the operation
        if (created != null) {
            LOGGER.info("Membership purchased: memberId=" + memberId +
                    ", type=" + type + ", cost=" + cost);
        } else {
            LOGGER.warning("Membership purchase failed for memberId=" + memberId);
        }
        return created;
    }

    /**
     * Retrieves all memberships for a specific member.
     * 
     * @param memberId the ID of the member
     * @return a list of Membership objects for the specified member
     */
    public List<Membership> getMembershipsForMember(int memberId) {
        return membershipDAO.getMembershipsByMemberId(memberId);
    }

    /**
     * Retrieves all membership records from the database.
     * 
     * @return a list of all Membership objects, or empty list if none found
     */
    public List<Membership> getAllMemberships() {
        return membershipDAO.getAllMemberships();
    }

    /**
     * Calculates the total revenue from all memberships.
     * 
     * @return the total revenue as BigDecimal, or zero if no memberships or on error
     */
    public BigDecimal getTotalRevenue() {
        return membershipDAO.getTotalRevenue();
    }

    /**
     * Calculates the total amount a specific member has spent on memberships.
     * Sums up the costs of all memberships purchased by the member.
     * 
     * @param memberId the ID of the member
     * @return the total expenses as BigDecimal, or zero if no memberships
     */
    public BigDecimal getTotalExpensesForMember(int memberId) {
        // Retrieve all memberships for the member
        List<Membership> memberships = membershipDAO.getMembershipsByMemberId(memberId);
        BigDecimal total = BigDecimal.ZERO;
        // Sum up the cost of all memberships
        for (Membership m : memberships) {
            if (m.getMembershipCost() != null) {
                total = total.add(m.getMembershipCost());
            }
        }
        return total;
    }
}
