package com.gymmanagement.service;

import com.gymmanagement.dao.WorkoutClassDAO;
import com.gymmanagement.model.WorkoutClass;
import com.gymmanagement.util.LoggerUtil;

import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Logger;

/**
 * Service class for managing workout class operations.
 * Acts as a facade between the application and the data access layer (DAO).
 * Provides business logic for creating, updating, retrieving, and deleting workout classes.
 * Ensures trainer ownership validation for update and delete operations.
 */
public class WorkoutClassService {

    private final WorkoutClassDAO workoutClassDAO;
    private static final Logger LOGGER = LoggerUtil.getLogger();

    /**
     * Default constructor that initializes the WorkoutClassDAO.
     */
    public WorkoutClassService() {
        this.workoutClassDAO = new WorkoutClassDAO();
    }

    /**
     * Constructor that accepts a WorkoutClassDAO instance (useful for dependency injection and testing).
     * 
     * @param workoutClassDAO the DAO instance for workout class database operations
     */
    public WorkoutClassService(WorkoutClassDAO workoutClassDAO) {
        this.workoutClassDAO = workoutClassDAO;
    }

    /**
     * Creates a new workout class for a trainer.
     * 
     * @param trainerId the ID of the trainer creating the class
     * @param type the type of workout (e.g., Yoga, HIIT, Pilates)
     * @param description a description of the workout class
     * @param scheduleTime the date and time when the class is scheduled
     * @param capacity the maximum number of members who can attend
     * @return the created WorkoutClass object with the generated ID, or null if creation fails
     */
    public WorkoutClass createClass(int trainerId,
                                    String type,
                                    String description,
                                    LocalDateTime scheduleTime,
                                    int capacity) {

        // Create a new WorkoutClass object with the provided details
        WorkoutClass workoutClass = new WorkoutClass(
                0,  // ID will be generated by the database
                type,
                description,
                trainerId,
                scheduleTime,
                capacity
        );

        // Delegate to DAO to persist the workout class
        WorkoutClass created = workoutClassDAO.createWorkoutClass(workoutClass);
        // Log the result of the operation
        if (created != null) {
            LOGGER.info("Workout class created by trainerId=" + trainerId +
                    ", type=" + type);
        } else {
            LOGGER.warning("Workout class creation failed for trainerId=" + trainerId);
        }
        return created;
    }

    /**
     * Updates an existing workout class.
     * The DAO ensures only the trainer who owns the class can update it.
     * 
     * @param workoutClass the WorkoutClass object containing updated details
     * @return true if the update was successful, false otherwise
     */
    public boolean updateClass(WorkoutClass workoutClass) {
        // Delegate to DAO to update the workout class (ownership verified in DAO)
        boolean updated = workoutClassDAO.updateWorkoutClass(workoutClass);
        // Log the result of the operation
        if (updated) {
            LOGGER.info("Workout class updated: id=" + workoutClass.getWorkoutClassId());
        } else {
            LOGGER.warning("Workout class update failed: id=" + workoutClass.getWorkoutClassId());
        }
        return updated;
    }

    /**
     * Deletes a workout class.
     * The DAO ensures only the trainer who owns the class can delete it.
     * 
     * @param classId the ID of the workout class to delete
     * @param trainerId the ID of the trainer attempting to delete the class
     * @return true if the deletion was successful, false otherwise
     */
    public boolean deleteClass(int classId, int trainerId) {
        // Delegate to DAO to delete the workout class (ownership verified in DAO)
        boolean deleted = workoutClassDAO.deleteWorkoutClass(classId, trainerId);
        // Log the result of the operation
        if (deleted) {
            LOGGER.info("Workout class deleted: id=" + classId + ", trainerId=" + trainerId);
        } else {
            LOGGER.warning("Workout class delete failed: id=" + classId + ", trainerId=" + trainerId);
        }
        return deleted;
    }

    /**
     * Retrieves all workout classes from the system.
     * 
     * @return a list of all WorkoutClass objects, or empty list if none found
     */
    public List<WorkoutClass> getAllClasses() {
        return workoutClassDAO.getAllClasses();
    }

    /**
     * Retrieves all workout classes created by a specific trainer.
     * 
     * @param trainerId the ID of the trainer
     * @return a list of WorkoutClass objects created by the trainer, or empty list if none found
     */
    public List<WorkoutClass> getClassesForTrainer(int trainerId) {
        return workoutClassDAO.getClassesByTrainerId(trainerId);
    }
}
